using UnityEngine;
using System;
using LuaInterface;
using SLua;
using System.Collections.Generic;
public class Lua_UnityEngine_HumanBodyBones : LuaObject {
	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr l) {
		int v = LuaDLL.lua_tointeger(l, 1);
		UnityEngine.HumanBodyBones o = (UnityEngine.HumanBodyBones)v;
		pushValue(l,o);
		return 1;
	}
	static public void reg(IntPtr l) {
		getTypeTable(l,"UnityEngine.HumanBodyBones");
		LuaDLL.lua_pushinteger(l, 0);
		LuaDLL.lua_setfield(l, -2, "Hips");
		LuaDLL.lua_pushinteger(l, 1);
		LuaDLL.lua_setfield(l, -2, "LeftUpperLeg");
		LuaDLL.lua_pushinteger(l, 2);
		LuaDLL.lua_setfield(l, -2, "RightUpperLeg");
		LuaDLL.lua_pushinteger(l, 3);
		LuaDLL.lua_setfield(l, -2, "LeftLowerLeg");
		LuaDLL.lua_pushinteger(l, 4);
		LuaDLL.lua_setfield(l, -2, "RightLowerLeg");
		LuaDLL.lua_pushinteger(l, 5);
		LuaDLL.lua_setfield(l, -2, "LeftFoot");
		LuaDLL.lua_pushinteger(l, 6);
		LuaDLL.lua_setfield(l, -2, "RightFoot");
		LuaDLL.lua_pushinteger(l, 7);
		LuaDLL.lua_setfield(l, -2, "Spine");
		LuaDLL.lua_pushinteger(l, 8);
		LuaDLL.lua_setfield(l, -2, "Chest");
		LuaDLL.lua_pushinteger(l, 9);
		LuaDLL.lua_setfield(l, -2, "Neck");
		LuaDLL.lua_pushinteger(l, 10);
		LuaDLL.lua_setfield(l, -2, "Head");
		LuaDLL.lua_pushinteger(l, 11);
		LuaDLL.lua_setfield(l, -2, "LeftShoulder");
		LuaDLL.lua_pushinteger(l, 12);
		LuaDLL.lua_setfield(l, -2, "RightShoulder");
		LuaDLL.lua_pushinteger(l, 13);
		LuaDLL.lua_setfield(l, -2, "LeftUpperArm");
		LuaDLL.lua_pushinteger(l, 14);
		LuaDLL.lua_setfield(l, -2, "RightUpperArm");
		LuaDLL.lua_pushinteger(l, 15);
		LuaDLL.lua_setfield(l, -2, "LeftLowerArm");
		LuaDLL.lua_pushinteger(l, 16);
		LuaDLL.lua_setfield(l, -2, "RightLowerArm");
		LuaDLL.lua_pushinteger(l, 17);
		LuaDLL.lua_setfield(l, -2, "LeftHand");
		LuaDLL.lua_pushinteger(l, 18);
		LuaDLL.lua_setfield(l, -2, "RightHand");
		LuaDLL.lua_pushinteger(l, 19);
		LuaDLL.lua_setfield(l, -2, "LeftToes");
		LuaDLL.lua_pushinteger(l, 20);
		LuaDLL.lua_setfield(l, -2, "RightToes");
		LuaDLL.lua_pushinteger(l, 21);
		LuaDLL.lua_setfield(l, -2, "LeftEye");
		LuaDLL.lua_pushinteger(l, 22);
		LuaDLL.lua_setfield(l, -2, "RightEye");
		LuaDLL.lua_pushinteger(l, 23);
		LuaDLL.lua_setfield(l, -2, "Jaw");
		LuaDLL.lua_pushinteger(l, 24);
		LuaDLL.lua_setfield(l, -2, "LeftThumbProximal");
		LuaDLL.lua_pushinteger(l, 25);
		LuaDLL.lua_setfield(l, -2, "LeftThumbIntermediate");
		LuaDLL.lua_pushinteger(l, 26);
		LuaDLL.lua_setfield(l, -2, "LeftThumbDistal");
		LuaDLL.lua_pushinteger(l, 27);
		LuaDLL.lua_setfield(l, -2, "LeftIndexProximal");
		LuaDLL.lua_pushinteger(l, 28);
		LuaDLL.lua_setfield(l, -2, "LeftIndexIntermediate");
		LuaDLL.lua_pushinteger(l, 29);
		LuaDLL.lua_setfield(l, -2, "LeftIndexDistal");
		LuaDLL.lua_pushinteger(l, 30);
		LuaDLL.lua_setfield(l, -2, "LeftMiddleProximal");
		LuaDLL.lua_pushinteger(l, 31);
		LuaDLL.lua_setfield(l, -2, "LeftMiddleIntermediate");
		LuaDLL.lua_pushinteger(l, 32);
		LuaDLL.lua_setfield(l, -2, "LeftMiddleDistal");
		LuaDLL.lua_pushinteger(l, 33);
		LuaDLL.lua_setfield(l, -2, "LeftRingProximal");
		LuaDLL.lua_pushinteger(l, 34);
		LuaDLL.lua_setfield(l, -2, "LeftRingIntermediate");
		LuaDLL.lua_pushinteger(l, 35);
		LuaDLL.lua_setfield(l, -2, "LeftRingDistal");
		LuaDLL.lua_pushinteger(l, 36);
		LuaDLL.lua_setfield(l, -2, "LeftLittleProximal");
		LuaDLL.lua_pushinteger(l, 37);
		LuaDLL.lua_setfield(l, -2, "LeftLittleIntermediate");
		LuaDLL.lua_pushinteger(l, 38);
		LuaDLL.lua_setfield(l, -2, "LeftLittleDistal");
		LuaDLL.lua_pushinteger(l, 39);
		LuaDLL.lua_setfield(l, -2, "RightThumbProximal");
		LuaDLL.lua_pushinteger(l, 40);
		LuaDLL.lua_setfield(l, -2, "RightThumbIntermediate");
		LuaDLL.lua_pushinteger(l, 41);
		LuaDLL.lua_setfield(l, -2, "RightThumbDistal");
		LuaDLL.lua_pushinteger(l, 42);
		LuaDLL.lua_setfield(l, -2, "RightIndexProximal");
		LuaDLL.lua_pushinteger(l, 43);
		LuaDLL.lua_setfield(l, -2, "RightIndexIntermediate");
		LuaDLL.lua_pushinteger(l, 44);
		LuaDLL.lua_setfield(l, -2, "RightIndexDistal");
		LuaDLL.lua_pushinteger(l, 45);
		LuaDLL.lua_setfield(l, -2, "RightMiddleProximal");
		LuaDLL.lua_pushinteger(l, 46);
		LuaDLL.lua_setfield(l, -2, "RightMiddleIntermediate");
		LuaDLL.lua_pushinteger(l, 47);
		LuaDLL.lua_setfield(l, -2, "RightMiddleDistal");
		LuaDLL.lua_pushinteger(l, 48);
		LuaDLL.lua_setfield(l, -2, "RightRingProximal");
		LuaDLL.lua_pushinteger(l, 49);
		LuaDLL.lua_setfield(l, -2, "RightRingIntermediate");
		LuaDLL.lua_pushinteger(l, 50);
		LuaDLL.lua_setfield(l, -2, "RightRingDistal");
		LuaDLL.lua_pushinteger(l, 51);
		LuaDLL.lua_setfield(l, -2, "RightLittleProximal");
		LuaDLL.lua_pushinteger(l, 52);
		LuaDLL.lua_setfield(l, -2, "RightLittleIntermediate");
		LuaDLL.lua_pushinteger(l, 53);
		LuaDLL.lua_setfield(l, -2, "RightLittleDistal");
		LuaDLL.lua_pushinteger(l, 54);
		LuaDLL.lua_setfield(l, -2, "LastBone");
		addMember(l,IntToEnum, "IntToEnum");
		LuaDLL.lua_pop(l, 1);
	}
}
