# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_any_cpu
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),debug_any_cpu)
  CSC = mcs
  RESGEN = resgen
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/slua-standalone.dll
  OBJDIR = obj/Any\ CPU/Debug/slua-standalone
  FLAGS = /unsafe /debug /noconfig /d:_DEBUG /d:DEBUG /d:TRACE /d:SLUA_STANDALONE /d:UNITY_STANDALONE_WIN /d:UNITY_STANDALONE
  DEPENDS =
  REFERENCES = 
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release_any_cpu)
  CSC = mcs
  RESGEN = resgen
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/slua-standalone.dll
  OBJDIR = obj/Any\ CPU/Release/slua-standalone
  FLAGS = /unsafe /optimize /noconfig /d:SLUA_STANDALONE /d:UNITY_STANDALONE_WIN /d:UNITY_STANDALONE
  DEPENDS =
  REFERENCES = 
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

FLAGS += /t:library 
REFERENCES += /r:System /r:System.Core

SOURCES += \
	../../Assets/Plugins/Slua_Managed/ByteArray.cs \
	../../Assets/Plugins/Slua_Managed/Coroutine.cs \
	../../Assets/Plugins/Slua_Managed/Helper.cs \
	../../Assets/Plugins/Slua_Managed/Logger.cs \
	../../Assets/Plugins/Slua_Managed/Lua3rdDLL.cs \
	../../Assets/Plugins/Slua_Managed/Lua3rdMeta.cs \
	../../Assets/Plugins/Slua_Managed/LuaArray.cs \
	../../Assets/Plugins/Slua_Managed/LuaByteArray.cs \
	../../Assets/Plugins/Slua_Managed/LuaDLL.cs \
	../../Assets/Plugins/Slua_Managed/LuaDLLWrapper.cs \
	../../Assets/Plugins/Slua_Managed/LuaObject.cs \
	../../Assets/Plugins/Slua_Managed/LuaObject_basetype.cs \
	../../Assets/Plugins/Slua_Managed/LuaObject_overload.cs \
	../../Assets/Plugins/Slua_Managed/LuaSocketMini.cs \
	../../Assets/Plugins/Slua_Managed/LuaState.cs \
	../../Assets/Plugins/Slua_Managed/LuaSvr.cs \
	../../Assets/Plugins/Slua_Managed/LuaSvrGameObject.cs \
	../../Assets/Plugins/Slua_Managed/LuaValueType.cs \
	../../Assets/Plugins/Slua_Managed/LuaVarObject.cs \
	../../Assets/Plugins/Slua_Managed/ObjectCache.cs \
	../../Assets/Plugins/Slua_Managed/SLuaSetting.cs \
	../../Assets/Plugins/Slua_Managed/Timer.cs \
	../../Assets/Plugins/Slua_Managed/WeakDictionary.cs \
	../../build/BytesHelper.cs \

EMBEDFILES += \

RESPONSE += $(OBJDIR)/slua-standalone.rsp
SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

all: $(TARGETDIR) $(OBJDIR) prebuild $(EMBEDFILES) $(COPYFILES) prelink $(TARGET)

$(TARGET): $(SOURCES) $(EMBEDFILES) $(DEPENDS) $(RESPONSE)
	$(SILENT) $(CSC) /nologo /out:$@ $(FLAGS) $(REFERENCES) @$(RESPONSE) $(patsubst %,/resource:%,$(EMBEDFILES))
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(RESPONSE): slua-standalone.make
	@echo Generating response file
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f $(RESPONSE)
else
	$(SILENT) if exist $(RESPONSE) del $(OBJDIR)\slua-standalone.rsp
endif
	@echo ../../Assets/Plugins/Slua_Managed/ByteArray.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/Coroutine.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/Helper.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/Logger.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/Lua3rdDLL.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/Lua3rdMeta.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/LuaArray.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/LuaByteArray.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/LuaDLL.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/LuaDLLWrapper.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/LuaObject.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/LuaObject_basetype.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/LuaObject_overload.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/LuaSocketMini.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/LuaState.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/LuaSvr.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/LuaSvrGameObject.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/LuaValueType.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/LuaVarObject.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/ObjectCache.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/SLuaSetting.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/Timer.cs >> $(RESPONSE)
	@echo ../../Assets/Plugins/Slua_Managed/WeakDictionary.cs >> $(RESPONSE)
	@echo ../../build/BytesHelper.cs >> $(RESPONSE)

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)
