# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),debug)
  CSC = csc
  RESGEN = resgen
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/slua-standalone.dll
  OBJDIR = obj/Debug/slua-standalone
  FLAGS = /debug /noconfig /d:_DEBUG /d:DEBUG /d:TRACE /d:SLUA_STANDALONE /d:UNITY_STANDALONE_WIN /d:UNITY_STANDALONE
  DEPENDS =
  REFERENCES = 
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  CSC = csc
  RESGEN = resgen
  TARGETDIR = ../bin
  TARGET = $(TARGETDIR)/slua-standalone.dll
  OBJDIR = obj/Release/slua-standalone
  FLAGS = /optimize /noconfig /d:SLUA_STANDALONE /d:UNITY_STANDALONE_WIN /d:UNITY_STANDALONE
  DEPENDS =
  REFERENCES = 
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

FLAGS += /t:library 
REFERENCES += /r:System.dll

SOURCES += \
	../../Assets/Plugins/Slua_Managed/Coroutine.cs \
	../../Assets/Plugins/Slua_Managed/Debugger/DebugInterface.cs \
	../../Assets/Plugins/Slua_Managed/Debugger/SLuaDebug.cs \
	../../Assets/Plugins/Slua_Managed/Helper.cs \
	../../Assets/Plugins/Slua_Managed/Logger.cs \
	../../Assets/Plugins/Slua_Managed/Lua3rdDLL.cs \
	../../Assets/Plugins/Slua_Managed/LuaDLL.cs \
	../../Assets/Plugins/Slua_Managed/LuaDLLWrapper.cs \
	../../Assets/Plugins/Slua_Managed/LuaObject.cs \
	../../Assets/Plugins/Slua_Managed/LuaObject_basetype.cs \
	../../Assets/Plugins/Slua_Managed/LuaObject_overload.cs \
	../../Assets/Plugins/Slua_Managed/LuaState.cs \
	../../Assets/Plugins/Slua_Managed/LuaSvr.cs \
	../../Assets/Plugins/Slua_Managed/LuaSvrGameObject.cs \
	../../Assets/Plugins/Slua_Managed/LuaValueType.cs \
	../../Assets/Plugins/Slua_Managed/LuaVarObject.cs \
	../../Assets/Plugins/Slua_Managed/ObjectCache.cs \
	../../Assets/Plugins/Slua_Managed/SLuaSetting.cs \
	../../Assets/Plugins/Slua_Managed/Timer.cs \
	../../Assets/Plugins/Slua_Managed/WeakDictionary.cs \

EMBEDFILES += \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

all: $(TARGETDIR) $(OBJDIR) prebuild $(EMBEDFILES) $(COPYFILES) prelink $(TARGET)

$(TARGET): $(SOURCES) $(EMBEDFILES) $(DEPENDS)
	$(SILENT) $(CSC) /nologo /out:$@ $(FLAGS) $(REFERENCES) $(SOURCES) $(patsubst %,/resource:%,$(EMBEDFILES))
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

